# Download all polls from telegram group with telethon
import random
import time

import telethon
from telethon.sync import TelegramClient
from telethon import functions, types
# InputMessagesFilterPolls
from inspect import getmembers, isfunction

from telethon.tl.types import InputPeerChat, Message

import db

from config import api_id, api_hash, chat_id, phone

message_to_start = db.next_message_id_to_process()
print(f"Starting from message id: {message_to_start}")

with TelegramClient("session_name", api_id, api_hash) as client:
    for (i, message) in enumerate(client.iter_messages(chat_id, filter=types.InputMessagesFilterEmpty(), reverse=True, min_id=message_to_start)):
        db.store_message(message)

        if hasattr(message, "poll") and message.poll:
            print("Before casting vote:", message.poll)
            # Try casting vote for a random option

            try:
                cast_vote_trial = client(functions.messages.SendVoteRequest(
                    # Input peer of the message
                    peer=message.peer_id,
                    # ID of the message
                    msg_id=message.id,
                    # The option ID, for instance `b'0'` for the first one
                    options=[random.choice(message.poll.poll.answers).option]
                ))
                print("Vote casting trial:", cast_vote_trial)
            except Exception as e:
                print("Vote casting trial failed:", e)

            message: Message = client.get_messages(chat_id, ids=message.id)
            # update message in db
            db.store_message(message)


            print("After casting a vote:", message.poll)
            for attribute, value in message.poll.__dict__.items():
                print(attribute, value)

            poll = message.poll.poll
            poll_results = message.poll.results

            print(poll.question)
            for answer in poll.answers:
                print(answer.text, answer.option)

            print(poll_results)

            # Check that results are visible to public
            if poll.public_voters:
                try:
                    # To get the voters, you need to use the GetPollVotesRequest
                    poll_votes = client(functions.messages.GetPollVotesRequest(
                        # Input peer of the message
                        peer=message.peer_id,
                        id=message.id,
                        limit=99999,
                    ))
                    print(poll_votes)
                    db.store_votes(message, poll_votes)
                except Exception as e:
                    print("Poll votes request failed:", e)

        print("\n\n\n\n\n")
        # if i > 10:
        #     break
        time.sleep(random.random() / 5)

"""
Message(id=4596, peer_id=PeerChannel(channel_id=1647040185), date=datetime.datetime(2023, 4, 23, 6, 26, 55,
                                                                                    tzinfo=datetime.timezone.utc),
        message='', out=False, mentioned=False, media_unread=False, silent=False,
        post=False, from_scheduled=False, legacy=False, edit_hide=True, pinned=False, noforwards=False, from_id=None,
        fwd_from=None, via_bot_id=None, reply_to=None, media=MessageMediaPoll(poll=Poll(id=5343531622278890328,
                                                                                        question='По вашему мнению, будет ли мобилизация в ближайший месяц?',
                                                                                        answers=[PollAnswer(text='Да',
                                                                                                            option=b'0'),
                                                                                                 PollAnswer(text='Нет',
                                                                                                            option=b'1'),
                                                                                                 PollAnswer(text='Тык',
                                                                                                            option=b'2')],
                                                                                        closed=False,
                                                                                        public_voters=True,
                                                                                        multiple_choice=False,
                                                                                        quiz=False, close_period=None,
                                                                                        close_date=None),
                                                                              results=PollResults(min=False, results=[],
                                                                                                  total_voters=55,
                                                                                                  recent_voters=[
                                                                                                      97124558,
                                                                                                      585846034,
                                                                                                      523876778],
                                                                                                  solution=None,
                                                                                                  solution_entities=[])),
        reply_markup=None, entities=[], views=None, forwards=None, replies=MessageReplies(replies=0, replies_pts=6622,
                                                                                          comments=False,
                                                                                          recent_repliers=[],
                                                                                          channel_id=None, max_id=None,
                                                                                          read_max_id=None),
        edit_date=datetime.datetime(
            2023, 4, 23, 6, 32, 18, tzinfo=datetime.timezone.utc), post_author=None, grouped_id=None,
        reactions=MessageReactions(results=[], min=False, can_see_list=True, recent_reactions=[]),
        restriction_reason=[],
        ttl_period=None)
"""


"""
VotesList(count=51, votes=[MessageUserVote(user_id=5764082456, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 14, 40, 20,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=1042620684, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 14, 13, 37,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=980404184, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 13, 21, 50,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=677227969, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 13, 4, 44,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=978827140, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 12, 28, 4,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=468638935, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 12, 26, 29,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=471133324, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 12, 14, 33,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=1034446526, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 12, 9, 3, tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=2083619244, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 11, 53, 35,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=1230472706, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 11, 22, 25,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=791603073, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 11, 20, 12,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=432919569, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 11, 4, 49,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=600118091, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 11, 4, 2, tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=97124558, option=b'1', date=datetime.datetime(2023, 4, 24, 11, 0, 13,
                                                                                                 tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=582993722, option=b'0',
                                           date=datetime.datetime(2023, 4, 24, 10, 57, 59,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=810400419, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 57, 10,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=478161177, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 49, 37,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=426085120, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 48, 32,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=427777843, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 47, 39,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=855780790, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 46, 8,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=314810613, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 44, 24,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=1058784063, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 42, 6,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=387656926, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 40, 5,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=539423830, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 39, 44,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=808864763, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 35, 38,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=1953731555, option=b'2',
                                           date=datetime.datetime(2023, 4, 24, 10, 34, 44,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=1352976876, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 34, 40,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=724530978, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 32, 59,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=1075802963, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 31, 45,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=531625784, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 30, 18,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=271450383, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 30, 3,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=585846034, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 29, 48,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=501476315, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 29, 11,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=572504937, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 29, 3,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=952955566, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 28, 54,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=910492159, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 28, 39,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=373588691, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 28, 36,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=417780330, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 28, 35,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=483458201, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 28, 5,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=555193574, option=b'2',
                                           date=datetime.datetime(2023, 4, 24, 10, 27, 55,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=577293884, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 27, 54,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=431784289, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 27, 51,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=452446667, option=b'2',
                                           date=datetime.datetime(2023, 4, 24, 10, 27, 45,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=248863894, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 27, 37,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=953049896, option=b'2',
                                           date=datetime.datetime(2023, 4, 24, 10, 27, 30,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=890402366, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 27, 30,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=557035278, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 27, 9,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=523876778, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 26, 55,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=368671528, option=b'1',
                                           date=datetime.datetime(2023, 4, 24, 10, 26, 54,
                                                                  tzinfo=datetime.timezone.utc)),
                           MessageUserVote(user_id=5422863690, option=b'0',
                                           date=datetime.datetime(2023, 4, 24, 10, 26, 53,
                                                                  tzinfo=datetime.timezone.utc))], users=[
    User(id=5764082456, is_self=True, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=True,
         attach_menu_enabled=False, access_hash=6343858599605164725, first_name='ВладимирЛатыпов',
         last_name='Подписочный', username='donRumataObserves', phone='79217617179',
         photo=UserProfilePhoto(photo_id=5251219139022929273, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08c\x80\xd2|\xc7\x8f\xaf4QE \xdc'),
         status=UserStatusOnline(expires=datetime.datetime(2023, 4, 24, 14, 44, 45, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]),
    User(id=1042620684, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=5094583704628283668, first_name='Данила', last_name=None,
         username='myznikovdanila', phone=None,
         photo=UserProfilePhoto(photo_id=4478021740369389484, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08$\xd4s )!R\x07\xdd\x1c\x83E\x14P\x07'),
         status=UserStatusRecently(), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None,
         lang_code=None, emoji_status=None, usernames=[]),
    User(id=980404184, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-4061492750689186725, first_name='Aleksandr', last_name='Kariakin',
         username='okayor', phone=None,
         photo=UserProfilePhoto(photo_id=4210803907597805567, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xa6\xad\x19Bq\xcf\xd6\x8a(\xa0\x0f'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 39, 30, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=677227969, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=8084209280409207080, first_name='фосфор 🌱', last_name=None,
                             username='phosphhor', phone=None,
                             photo=UserProfilePhoto(photo_id=2908671979247740845, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\x04,\xd2\xe5\xc8\x1by\x18=(\xa2\x8aM\xd8\xb5\x1b\x9f'),
                             status=UserStatusOffline(
                                 was_online=datetime.datetime(2023, 4, 24, 13, 33, 46, tzinfo=datetime.timezone.utc)),
                             bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None,
                             emoji_status=None, usernames=[]),
    User(id=978827140, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=4172306692543536919, first_name='гейлик)', last_name=None,
         username='exrcisr', phone=None,
         photo=UserProfilePhoto(photo_id=4204030555193452484, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xce\xda\x0c\x03\xe6\xe7=(\xa2\x8a\x91\x9f'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 12, 36, 33, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=468638935, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-4239585468792541295, first_name='Маша', last_name='Ткачёва',
                             username='masha_tk02', phone=None,
                             photo=UserProfilePhoto(photo_id=2012788899913508789, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\x8e\xd5\xd9\x02\xf1\x9c\xa8\x14QEJch'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=471133324, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-3303323289353681726, first_name='kristina', last_name='yakovleva',
         username='kristinadriam', phone=None,
         photo=UserProfilePhoto(photo_id=2023502219092010942, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xce\xff\x00\x96a03\xd7=\xe8\xa2\x8aC?'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 38, 44, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]),
    User(id=1034446526, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-5787127036768482068, first_name='Александр', last_name='Забурдаев 🌱',
         username='peppermint1717', phone=None,
         photo=UserProfilePhoto(photo_id=4442913999087052724, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xd5$\x87\x19=\xe8\xa2\x8ab?'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 12, 59, 3, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]),
    User(id=2083619244, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=4005412272183934465, first_name='Алина', last_name='Мельникова',
         username='Meylinabc', phone=None,
         photo=UserProfilePhoto(photo_id=5260491878925713900, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08V,\x91\xa9~\xa1\xbaz\n(\xa2\x84\x86\xcf'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 8, 53, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]),
    User(id=1230472706, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=9163085458150444517, first_name='Миша', last_name='Оларь🤪',
         username='TOPKEDbl', phone=None,
         photo=UserProfilePhoto(photo_id=5294283869861823974, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xa8\x1d\x96`\xc0g\x9c\x10(\xa2\x8aC?'),
         status=UserStatusRecently(), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None,
         lang_code=None, emoji_status=None, usernames=[]),
    User(id=791603073, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=2357420355980524287, first_name='Катя', last_name=None,
         username='kkotiaa', phone=None,
         photo=UserProfilePhoto(photo_id=3399909310404339658, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xad\xe4\x96\x80\xc8>\xefR(\xa2\x8aC?'),
         status=UserStatusRecently(), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None,
         lang_code=None, emoji_status=None, usernames=[]),
    User(id=432919569, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=True,
         attach_menu_enabled=False, access_hash=7797532950430282454, first_name='Михаил', last_name='Минаев',
         username='true_minmise', phone=None,
         photo=UserProfilePhoto(photo_id=1859375391109654458, dc_id=2, has_video=True, personal=False,
                                stripped_thumb=b'\x01\x08\x08\x0b\xab\xea\x9b\x84\xad\x90\x98\xfch\xa2\x8a\xbb\x99\xb8\xdc'),
         status=UserStatusOnline(expires=datetime.datetime(2023, 4, 24, 14, 45, 46, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None,
         emoji_status=EmojiStatus(document_id=5397924123202561466), usernames=[]),
    User(id=600118091, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-6020452424118478971, first_name='Yura', last_name='Filatov',
         username='YuriFilatov', phone=None,
         photo=UserProfilePhoto(photo_id=2577487575039190961, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xa7\xf6U\xdf\xb7\x9c\xe34QE\x1a\x8f\x9dv?'),
         status=UserStatusOnline(expires=datetime.datetime(2023, 4, 24, 14, 46, 10, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=97124558, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-9142718775020754084, first_name='Osipenkova Iulia', last_name=None,
                             username='Jojotlg', phone=None,
                             photo=UserProfilePhoto(photo_id=417146800704694219, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\x92\x15\x93\xcd\x0e\xcb\xf3*\xe0g\xd2\x8a(\xa6+\x9f'),
                             status=UserStatusOffline(
                                 was_online=datetime.datetime(2023, 4, 24, 14, 14, 48, tzinfo=datetime.timezone.utc)),
                             bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None,
                             emoji_status=None, usernames=[]),
    User(id=582993722, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-3477630507901223180, first_name='Oleg', last_name='Terentev',
         username='terentev_oleg', phone=None,
         photo=UserProfilePhoto(photo_id=2503938970219554731, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\x93\xec\x08\xd2`\x9f\x93\x19\xe3\xad\x14Q@\x1f'),
         status=UserStatusRecently(), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None,
         lang_code=None, emoji_status=None, usernames=[]),
    User(id=810400419, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-9045199820051296482, first_name='Таня', last_name='Елфимова',
         username='fllbdemmmt', phone=None,
         photo=UserProfilePhoto(photo_id=3480643296725936050, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\x866P\x81O\xdf\xdf\xf8QE\x15,\xa3'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 41, 10, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=478161177, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=4725954793205048603, first_name='Ivan \\', last_name='Kalinin ///',
                             username='jeck5iv', phone=None,
                             photo=UserProfilePhoto(photo_id=2053686617888106423, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\xb4\xaa2@\x0b\xb8\x1a(\xa2\xa9\x10\xcf'),
                             status=UserStatusOffline(
                                 was_online=datetime.datetime(2023, 4, 24, 14, 15, 52, tzinfo=datetime.timezone.utc)),
                             bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None,
                             emoji_status=None, usernames=[]),
    User(id=426085120, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-4242212148739334313, first_name='Egor', last_name='Kokush',
         username='egoluback', phone=None,
         photo=UserProfilePhoto(photo_id=1830021656168474566, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xad\x12\xc4\xdb\xb6\x8fnz\x8a(\xa2\x9d\x89m\xdc'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 38, 35, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=427777843, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=2515972847225053227, first_name='Dan', last_name='Nesterov',
                             username='DanNesterov', phone=None, photo=None, status=UserStatusRecently(),
                             bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None,
                             emoji_status=None, usernames=[]),
    User(id=855780790, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-8041032592347568986, first_name='Равиль', last_name='Гареев',
         username='ravilgareev', phone=None, photo=None,
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 37, 54, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=314810613, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-8151976401808254683, first_name='Andrey', last_name='Sheremeev',
                             username='aasheremeev', phone=None,
                             photo=UserProfilePhoto(photo_id=1352101287724951477, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08O2!\xc3\xfe$\x1e\x08\xa2\x8a(\xb0\x9b?'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=1058784063, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-7160802157188854605, first_name='Владислав', last_name='Москвитин',
         username='lad1chka', phone=None,
         photo=UserProfilePhoto(photo_id=4547442924567242669, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xca\x1c\x81E\x14W\xa5\x08\xa6\x88?'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 39, 41, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=387656926, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=4609477567618563853, first_name='Alisa', last_name='Gladchenko',
                             username='alicegl', phone=None,
                             photo=UserProfilePhoto(photo_id=1664973819694131120, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08c])9P\x008\xear1E\x14R\xbbEY4\x7f'),
                             status=UserStatusOffline(
                                 was_online=datetime.datetime(2023, 4, 24, 14, 39, 31, tzinfo=datetime.timezone.utc)),
                             bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None,
                             emoji_status=None, usernames=[]),
    User(id=539423830, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-3737604322414786609, first_name='Егор', last_name='Шамшура',
         username='medicalwealth', phone=None, photo=None, status=UserStatusRecently(), bot_info_version=None,
         restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=808864763, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-6768939045870135444, first_name='Илья', last_name='Аникеев',
         username='CurledCypress', phone=None,
         photo=UserProfilePhoto(photo_id=3474047704428029876, dc_id=2, has_video=True, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xce\xdd\x07\xd96\xec\xfd\xef\xf7\xa8\xa2\x8a\x12\xb0\x1f'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 18, 23, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]),
    User(id=1953731555, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-3608558078713139527, first_name='Nikita Ivlev', last_name=None,
         username='viphwydon', phone=None,
         photo=UserProfilePhoto(photo_id=5332470814932583862, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xb3\xc0L\xe7\x9a(\xa2\xad\x92\x7f'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 40, 23, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]),
    User(id=1352976876, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=True,
         attach_menu_enabled=False, access_hash=-7557322690059544128, first_name='Давид Дашевский', last_name=None,
         username='svalbardpyramiden', phone=None,
         photo=UserProfilePhoto(photo_id=5323328715050042762, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xcbI0pA\xc61\xc5\x14QWv4\xcf'),
         status=UserStatusOnline(expires=datetime.datetime(2023, 4, 24, 14, 46, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None,
         emoji_status=EmojiStatus(document_id=5190954755924438448), usernames=[]),
    User(id=724530978, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-9169014691248649978, first_name='Матвей', last_name='Смирнов',
         username='vdaleke', phone=None,
         photo=UserProfilePhoto(photo_id=3111836855905134526, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\x98J\xbb\x0es\xbb<QE\x15\xd5\x18$q\xa8\xc6Kc'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 38, 55, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]),
    User(id=1075802963, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-1035330214181129443, first_name='Влад', last_name='Цирульников',
         username='SLIGUP', phone=None,
         photo=UserProfilePhoto(photo_id=5255985448914895159, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\x91e\xf9{\x0c{QE\x15\x8b\xe8f\xd9'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 20, 20, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=531625784, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-4994716097365500748, first_name='Лиза', last_name='Петрова',
                             username='lizzinni', phone=None,
                             photo=UserProfilePhoto(photo_id=2283315356446599146, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\x88\xca\xa5\x89\xce1\x9e~\xb4QE g'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=271450383, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-3457630058023447297, first_name='Vasily', last_name='Lupuleac',
         username='Relayer1974', phone=None,
         photo=UserProfilePhoto(photo_id=1165870517927913399, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\x8b\xcc\x89X\xf23\xbcc\x8e\x82\x8a(\xa9*\xe7'),
         status=UserStatusRecently(), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None,
         lang_code=None, emoji_status=None, usernames=[]),
    User(id=585846034, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=6098553629937785983, first_name='Konstantin', last_name='Suspitsyn',
         username='thebestkostya', phone=None,
         photo=UserProfilePhoto(photo_id=2516189556977543094, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08z$/\x07\x93\xb0\x13\x8c\xee\xc7S\xebE\x14Q\x1d\x82j\xcc'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 13, 44, 1, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=501476315, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-2587486042991611087, first_name='Boris', last_name='Mikhaylov',
                             username='outofreality11', phone=None,
                             photo=UserProfilePhoto(photo_id=2153824373099833266, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\xaa\xdbP\x85\x03\xa7C\x9e(\xa2\x8a,\x07'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=572504937, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-8445516509372847224, first_name='Камиль', last_name='Габидуллин',
         username='gabik2004', phone=None,
         photo=UserProfilePhoto(photo_id=2458889981669779387, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\x82H HRO3\n\xc7\xd3\xf9QE\x156\x1d\xcf'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 40, 18, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=952955566, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=True, attach_menu_enabled=False,
                             access_hash=4834943511094751996, first_name='maya', last_name='ovsiannikova',
                             username='mayaoaoa', phone=None,
                             photo=UserProfilePhoto(photo_id=4092912990967409047, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\x97kn\x03<\xe38\x07\xad\x14QRQ'),
                             status=UserStatusOffline(
                                 was_online=datetime.datetime(2023, 4, 24, 14, 38, 13, tzinfo=datetime.timezone.utc)),
                             bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None,
                             emoji_status=EmojiStatus(document_id=5397744443245732432), usernames=[]),
    User(id=910492159, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=7397348283641509653, first_name='Максим', last_name='Назаров',
         username='Makssnazaroff', phone=None, photo=None,
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 13, 44, 20, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=373588691, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-509564033540973233, first_name='тимуррр сайфутдинов)', last_name=None,
                             username='timurio111', phone=None,
                             photo=UserProfilePhoto(photo_id=1604551210456688599, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08O-\xf1\xe6oo\xa6\x0e(\xa2\x8a\xcb\x99\x94\x7f'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=417780330, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-8211549330202273892, first_name='Milyaushá', last_name='Sabirova',
         username='milyaushas', phone=None,
         photo=UserProfilePhoto(photo_id=1794352854718326897, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08`+\xe4\x95d\xf9\xfad\x0e\x94QEG34\xe5G'),
         status=UserStatusRecently(), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None,
         lang_code=None, emoji_status=None, usernames=[]),
    User(id=483458201, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-8595849547767426831, first_name='Tima Sosnin', last_name=None,
         username='If9090', phone=None,
         photo=UserProfilePhoto(photo_id=2076437162734233522, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xd3\x1eg\xda\xd8c\xe4\xda\x0es\xde\x8a(\xa0\x0f'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 32, 10, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=555193574, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=3287608918878629219, first_name='Даня', last_name='Нейков🗣📣',
                             username='navcolo_Tebe', phone=None,
                             photo=UserProfilePhoto(photo_id=2384538243735594978, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08G\\\xa3ars\xe9E\x14Vnm0?'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=577293884, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=9190751248217831843, first_name='Anya', last_name='Maksimova',
         username='anpalmak', phone=None,
         photo=UserProfilePhoto(photo_id=2479458352417056724, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xab:*[\xa7\x96\x9e\xbb\x89\xa2\x8a)E\xe89#'),
         status=UserStatusRecently(), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None,
         lang_code=None, emoji_status=None, usernames=[]),
    User(id=431784289, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=1879856341512191510, first_name='Федор', last_name='Бондарь',
         username='fedyamathboi', phone=None,
         photo=UserProfilePhoto(photo_id=1854499400637851589, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08{\\\x13u\xdb\x18\xdb\xf8u\xcd\x14Q@\x1f'),
         status=UserStatusRecently(), bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None,
         lang_code=None, emoji_status=None, usernames=[]),
    User(id=452446667, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-425867254312094095, first_name='Шредингер кота', last_name=None,
         username='kakoy_to_kot', phone=None,
         photo=UserProfilePhoto(photo_id=1943243638405441478, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xb0$t\x9f\x08\x80\x82\xdd\xcd\x14QHg'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 13, 44, 45, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=248863894, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-212405772471230724, first_name='Elizaveta', last_name='Zhemchuzhina',
                             username='lizazhemchuzhina', phone=None,
                             photo=UserProfilePhoto(photo_id=1068862286341449886, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\xb8Y\x84\xb8\x08H\xdd\xd7\x14QE\x00\x7f'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=953049896, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-5143385298566287676, first_name='ostap', last_name='manasihin',
         username='p6tso', phone='79920083654',
         photo=UserProfilePhoto(photo_id=4093318135232440254, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xccXC\xc2\xd2\t\x14\x15\xfe\x13\xd6\x8a(\xa43'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 38, 38, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=890402366, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-190739044944287944, first_name='Тanya', last_name='Shimanskaya',
                             username='three_quartness', phone=None,
                             photo=UserProfilePhoto(photo_id=3824249042707261367, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\x86\xde0\xf6\xed&>\xe9\xc1\xa2\x8a)!\xb3'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=557035278, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-3795816516156621290, first_name='Timur', last_name='Abdulkadirov',
         username='Shadow_135', phone=None,
         photo=UserProfilePhoto(photo_id=2392448302184507307, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\xa0\xc1E\xb89\xf9\x83`\xe4\xd1E\x14\x903'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 30, 19, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]), User(id=523876778, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
                             bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False,
                             bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False,
                             bot_attach_menu=False, premium=False, attach_menu_enabled=False,
                             access_hash=-4015240269243268657, first_name='Vladislav', last_name='Naumkin',
                             username='N4V1S', phone=None,
                             photo=UserProfilePhoto(photo_id=2250033629100091312, dc_id=2, has_video=False,
                                                    personal=False,
                                                    stripped_thumb=b'\x01\x08\x08\x81U"?!\xe3\xebE\x14U\x08'),
                             status=UserStatusRecently(), bot_info_version=None, restriction_reason=[],
                             bot_inline_placeholder=None, lang_code=None, emoji_status=None, usernames=[]),
    User(id=368671528, is_self=False, contact=True, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=642036437865120895, first_name='Марк', last_name='Ипатов',
         username='c0deEater', phone='79523695546',
         photo=UserProfilePhoto(photo_id=1583432156182587378, dc_id=2, has_video=False, personal=False,
                                stripped_thumb=b'\x01\x08\x08\x8c1\x11\xec\x08\x01\xeb\xbb4QEM\x8b?'),
         status=UserStatusOffline(was_online=datetime.datetime(2023, 4, 24, 14, 39, 22, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[]),
    User(id=5422863690, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False,
         bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False,
         support=False, scam=False, apply_min_photo=True, fake=False, bot_attach_menu=False, premium=False,
         attach_menu_enabled=False, access_hash=-3628717427765867192, first_name='Даниил', last_name='Марценюк',
         username='engartion', phone=None, photo=None,
         status=UserStatusOnline(expires=datetime.datetime(2023, 4, 24, 14, 46, 14, tzinfo=datetime.timezone.utc)),
         bot_info_version=None, restriction_reason=[], bot_inline_placeholder=None, lang_code=None, emoji_status=None,
         usernames=[])], next_offset='1682332013_5422863690')
"""
